name:                smt2-parser
version:             0.1.0.0
github:              "crvdgc/smt2-parser"
license:             BSD3
author:              "crvdgc"
maintainer:          "yokis1997@pku.edu.cn"
copyright:           "2020 crvdgc"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crvdgc/smt2-parser#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4
- text
- parsec

library:
  source-dirs: src

tests:
  smt2-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smt2-parser
    - HUnit >= 1.0 && < 2.0
